version: '3'
services:
  app:
    build: 
      context: ../
      dockerfile: dev/Dockerfile
    container_name: starlette-app
    depends_on:
      - redis
      - mongodb
    env_file:
      - .env
    image: starlette-app-img
    networks:
      - starlette-network
    ports:
      - "80:8000"
    volumes:
      - '../app:/app/host_app'
    working_dir: /app/host_app
  mongodb:
    container_name: starlette-app-mongodb
    image: mongo
    networks: 
      - starlette-network
    ports:
      - "27017:27017"
  redis: 
    container_name: starlette-app-redis
    image: redis
    networks:        
      - starlette-network
    ports:
      - "6379:6379"
networks:
  starlette-network:
